# -------------------------------
# MapProxy example configuration.
# -------------------------------
#

# This is a minimal MapProxy configuration.
# See full_example.yaml and the documentation for more options.
#
# Starts the following services:
# Demo:
#     http://localhost:8080/demo
# WMS:
#     capabilities: http://localhost:8080/service?REQUEST=GetCapabilities
# WMTS:
#     capabilities: http://localhost:8080/wmts/1.0.0/WMTSCapabilities.xml
#     first tile: http://localhost:8080/wmts/osm/webmercator/0/0/0.png
# Tile service (compatible with OSM/etc.)
#     first tile: http://localhost:8080/tiles/osm/webmercator/0/0/0.png
# TMS:
#     note: TMS is not compatible with OSM/Google Maps/etc.
#     fist tile: http://localhost:8080/tms/1.0.0/osm/webmercator/0/0/0.png
# KML:
#     initial doc: http://localhost:8080/kml/osm/webmercator

services:
  demo:
  tms:
    use_grid_names: false
    # origin for /tiles service
    origin: 'nw'
  kml:
    use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

layers:
  - name: osm
    title: Omniscale OSM WMS - osm.omniscale.net
    sources: [osm_cache]
  - name: databc
    title: DataBC WMS cache
    sources: [databc_cache]

caches:
  osm_cache:
    grids: [webmercator]
    sources: [osm_wms]
  databc_cache:
    grids: [webmercator]
    sources: [databc_wms]

sources:
  databc_wms:
    type: wms
    req:
      url: https://openmaps.gov.bc.ca/geo/pub/ows
      layers: WHSE_FOREST_TENURE.FTEN_RANGE_POLY_SVW
      transparent: true
  osm_wms:
    type: wms
    req:
      url: https://maps.omniscale.net/v2/demo/style.default/service?
      layers: osm
grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
globals:

​

​
